name: system_one
description: An unofficial Dart client for the System One API (TypeSafe AI, Ollama, and other compatible servers).
version: 0.2.0
publish_to: none
repository: https://github.com/andyhorn/system_one_dart
executables:
  system_one: system_one

environment:
  sdk: ^3.13.2

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  http: ^1.2.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
